<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ReportV2.Core\ReportV2.Core.csproj" />
    <ProjectReference Include="..\ReportV2.Application\ReportV2.Application.csproj" />
    <ProjectReference Include="..\ReportV2.Infrastructure\ReportV2.Infrastructure.csproj" />
    <ProjectReference Include="..\ReportV2.Rendering\ReportV2.Rendering.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
